options:
  verbose:
    type: boolean
    default: true
    description: Toogle verbose logging.
  cleanup:
    type: boolean
    default: true
    description: |
        Toggle uninstall step of prerequisities by install hook.
        Disable this if you planned to merge services into same unit, see ticket #87.
  root_secret:
    type: string
    default: "toto"
    description: |
        Secret key used by API clients to manage users.
        Please change it in production.
  node_secret:
    type: string
    default: "abcd"
    description: |
        Secret key used by workers/nodes to callback API when they finish their task.
        Please change it in production.
  mongo_admin_password:
    type: string
    default: "Mongo_admin_1234"
    description: Database administrator password.
  mongo_node_password:
    type: string
    default: "Mongo_user_1234"
    description: Database nodes password.
  rabbit_password:
    type: string
    default: "Alice_in_wonderland"
    description: |
        Messaging queue user's password.
        This secret is then forwared by the coordinator to managed units (transform, publish).
  charms_release:
    type: string
    default: "raring"
    description: The default Ubuntu release for the units deployed with the units management API of the orchestrator.
  email_server:
    type: string
    default: ""
    description: |
        SMTP mailing server address.
        Please set to enable mailing functionnalitiy.
  email_tls:
    type: boolean
    default: true
    description: Enable TLS layer.
  email_address:
    type: string
    default: "someone@oscied.org"
    description: Sender e-mail address of any mail sended by the orchestrator.
  email_username:
    type: string
    default: "someone"
    description: Sender e-mail account username.
  email_password:
    type: string
    default: "1234"
    description: Sender e-mail account password.
  storage_address:
    type: string
    default: ""
    description: |
        Shared storage hostname / IP address (see interface mount of nfs charm).
        The 'storage' options override and disable storage relation.
  storage_nat_address:
    type: string
    default: ""
    description: Shared storage reacheable (public) address e.g. when storage is behind a NAT/FW.
  storage_fstype:
    type: string
    default: ""
    description: Shared storage filesystem type (e.g. nfs).
  storage_mountpoint:
    type: string
    default: ""
    description: Shared storage mountpoint (e.g. for nfs - /srv/data).
  storage_options:
    type: string
    default: ""
    description: Shared storage options (e.g. for nfs - rw,sync,no_subtree_check).
  plugit_api_url:
    type: string
    default: ""
    description: |
        The URL of your running EBU's PlugIt authentication API.
        If set, the orchestrator will switch from standalone users management to EBU's PlugIt-based users management.
  plugit_allowed_networks:
    type: string
    default: "127.0.0.1/32"
    description: |
        Comma-delimited networks allowed to access the API, e.g. '129.194.0.0/16,4.4.4.4/32'.
        Defaults means anyone can mount the storage.
        This option is useful to grant an access to this service to your clients that are running
        outside of the storage's JuJu environment.
        This option can be changed while the service is running.
