options:
  verbose:
    type: string
    default: "true"
    description: Toogle verbose logging.
  cleanup:
    type: string
    default: "true"
    description: |
        Toggle uninstall step of prerequisities by install hook.
        Disable this if you planned to merge services into same unit, see ticket #87.
  allowed_ips:
    type: string
    default: "*"
    description: |
        Comma-delimited IP addresses (wild-cald patterns) of the clients which should be allowed to
        access the volume, e.g. '30.0.0.*,27.32.*'.
        Defaults means anyone can mount the storage.
        This option is useful to grant an access to this service to your clients that are running
        outside of the storage's JuJu environment.
        This option can be changed while the service is running.
  replica_count:
    type: int
    default: 1
    description: |
        Set replica count.
        Medias volume is not created (and started) until N nodes are connected.
        Then, the volume will be expanded of N bricks every time you'll add exactly N new nodes.
        Default means no redundancy at all.
  bricks_root_path:
    type: string
    default: '/mnt'
    description: |
        Set the root path where bricks are stored.
        This option is useful to allow you using the attached EBS storage (or whatsoever).
