options:
  verbose:
    type: boolean
    default: true
    description: Toogle verbose logging.
  cleanup:
    type: boolean
    default: true
    description: |
        Toggle uninstall step of prerequisities by install hook.
        Disable this if you planned to merge services into same unit, see ticket #87.
  concurrency:
    type: int
    default: 1
    description: |
        Amount of tasks the worker can handle simultaneously.
        Default value is conservative.
  rabbit_queues:
    type: string
    default: "transform"
    description: |
        Worker connect to queues to receive tasks.
        For example "transform_amazon" for amazon, "transform_private,transform_amazon" for both.
  mongo_connection:
    type: string
    default: ""
    description: |
        Orchestrator database connection.
        The 'connection' options override and disable transform relation.
  rabbit_connection:
    type: string
    default: ""
    description: Orchestrator message broker connection.
  api_nat_socket:
    type: string
    default: ""
    description: Orchestrator API reacheable (public) address (ip:port) e.g. when orchestra is behind a NAT/FW.
  storage_address:
    type: string
    default: ""
    description: |
        Shared storage hostname / IP address (see interface mount of nfs charm).
        The 'storage' options override and disable storage relation.
  storage_nat_address:
    type: string
    default: ""
    description: Shared storage reacheable (public) address e.g. when storage is behind a NAT/FW.
  storage_fstype:
    type: string
    default: ""
    description: Shared storage filesystem type (e.g. nfs).
  storage_mountpoint:
    type: string
    default: ""
    description: Shared storage mountpoint (e.g. for nfs - /srv/data).
  storage_options:
    type: string
    default: ""
    description: Shared storage options (e.g. for nfs - rw,sync,no_subtree_check)
  open_hevc_origin:
    type: string
    default: ""
    description: |
      * '' : Do not install openHEVC at all
      * 'openHEVC.tar.bz2' : Compile openHEVC from local archive of sources
  x264_origin:
    type: string
    default: ""
    description: |
      * '' : Get x264 from Ubuntu default repository
      * 'x264.tar.bz2' : Compile x264 from local archive of sources
  ffmpeg_origin:
    type: string
    default: "ppa:jon-severinsson/ffmpeg"
    description: |
      * '' : Get ffmpeg from Ubuntu default repository
      * 'ppa:jon-severinsson/ffmpeg' : Get ffmpeg from this PPA repository
      * 'ffmpeg.tar.bz2' : Compile ffmpeg from local archive of sources
  gpac_origin:
    type: string
    default: "gpac_0.5.1.DEV-r4927_amd64.deb"
    description: |
      * '' : Get GPAC/DashCast from Ubuntu default repository
      * 'gpac.tar.bz2' : Compile GPAC/DashCast from local archive of sources
      * 'gpac_0.5.1.DEV-r4927_i386.deb' : Install GPAC/DashCast from a debian package
